import { z } from "zod";

/**
 * Contracts of background jobs: queue names, payload shapes, retry rules and job ids.
 * Pure data and functions; the worker and the web app wire them to the queue library.
 *
 * Payloads travel through Redis unencrypted, so they carry identifiers only: never tokens,
 * amounts, e-mail addresses or any text taken from an external system.
 */

export const QUEUE_NAMES = {
  sync: "sync",
  actions: "actions",
  scheduled: "scheduled",
  deadLetter: "dead-letter",
} as const;

export type QueueName = (typeof QUEUE_NAMES)[keyof typeof QUEUE_NAMES];
/** Queues with a worker; the dead-letter queue is only ever written to. */
export type ProcessedQueueName = Exclude<QueueName, "dead-letter">;

export const PROCESSED_QUEUES: readonly ProcessedQueueName[] = [
  QUEUE_NAMES.sync,
  QUEUE_NAMES.actions,
  QUEUE_NAMES.scheduled,
];

// ---------------------------------------------------------------------------------------
// Retries
// ---------------------------------------------------------------------------------------

export interface RetryPolicy {
  /** Total number of tries, the first one included. */
  attempts: number;
  /** Wait before the second try; doubles with every further one. */
  baseDelayMs: number;
  /** Upper bound of the wait. */
  maxDelayMs: number;
  /** Share of the wait (0–1) that is randomised away so that retries do not arrive in step. */
  jitter: number;
}

export const DEFAULT_RETRY_POLICY: RetryPolicy = {
  attempts: 3,
  baseDelayMs: 5_000,
  maxDelayMs: 10 * 60_000,
  jitter: 0.2,
};

/**
 * Wait before the next try after `attemptsMade` failed ones: exponential, capped, with
 * jitter taken off the top. `random` returns a number in [0, 1) and exists for tests.
 */
export function retryDelayMs(
  policy: RetryPolicy,
  attemptsMade: number,
  random: () => number = Math.random,
): number {
  if (!Number.isInteger(attemptsMade) || attemptsMade < 1) {
    throw new RangeError("attemptsMade must be a positive integer");
  }
  const exponential = policy.baseDelayMs * 2 ** Math.min(attemptsMade - 1, 30);
  const capped = Math.min(exponential, policy.maxDelayMs);
  return Math.round(capped * (1 - policy.jitter * random()));
}

// ---------------------------------------------------------------------------------------
// Job ids
// ---------------------------------------------------------------------------------------

/** Thrown when a job id cannot be built from the given parts. */
export class InvalidJobIdError extends Error {
  override name = "InvalidJobIdError";
}

const JOB_ID_PART = /^[A-Za-z0-9_.-]+$/;
const MAX_JOB_ID_LENGTH = 200;

/**
 * Builds a deterministic job id, e.g. `sync.fakturoid.<connectionId>.2026-10-08T07`.
 * The same parts always give the same id, which is what makes enqueueing idempotent.
 * The queue library forbids `:` in ids and ids made of digits only.
 */
export function buildJobId(...parts: readonly string[]): string {
  if (parts.length === 0) {
    throw new InvalidJobIdError("A job id needs at least one part.");
  }
  for (const part of parts) {
    if (!JOB_ID_PART.test(part)) {
      throw new InvalidJobIdError("Job id parts may contain only letters, digits, _ . and -");
    }
  }
  const id = parts.join(".");
  if (/^\d+$/.test(id)) {
    throw new InvalidJobIdError("A job id must not consist of digits only.");
  }
  if (id.length > MAX_JOB_ID_LENGTH) {
    throw new InvalidJobIdError(`A job id may have at most ${MAX_JOB_ID_LENGTH} characters.`);
  }
  return id;
}

/** Makes an arbitrary id (e.g. one generated by the scheduler) safe to embed in another id. */
export function sanitizeJobIdPart(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9_.-]/g, "_");
  return cleaned === "" ? "_" : cleaned;
}

// ---------------------------------------------------------------------------------------
// Job definitions
// ---------------------------------------------------------------------------------------

export interface JobDefinition<TData> {
  /** Unique across all queues, e.g. `maintenance.cleanup-oauth-requests`. */
  name: string;
  queue: ProcessedQueueName;
  /** Payloads are validated when enqueued and again when processed. */
  schema: z.ZodType<TData>;
  retry: RetryPolicy;
}

export function defineJob<TData>(definition: JobDefinition<TData>): JobDefinition<TData> {
  return definition;
}

const emptyPayloadSchema = z.strictObject({});
/** Payload of jobs that need no input. */
export type EmptyPayload = z.infer<typeof emptyPayloadSchema>;

/** Daily removal of expired and used OAuth requests (table `oauth_requests`). */
export const cleanupOAuthRequestsJob = defineJob<EmptyPayload>({
  name: "maintenance.cleanup-oauth-requests",
  queue: QUEUE_NAMES.scheduled,
  schema: emptyPayloadSchema,
  retry: DEFAULT_RETRY_POLICY,
});

// ---------------------------------------------------------------------------------------
// Schedules
// ---------------------------------------------------------------------------------------

/** Planning happens in Czech local time (morning brief at 7:00, nightly maintenance). */
export const SCHEDULE_TIME_ZONE = "Europe/Prague";

export interface JobSchedule {
  /** Stable id; registering the same id again updates the schedule instead of adding one. */
  id: string;
  /** Cron expression evaluated in {@link SCHEDULE_TIME_ZONE}. */
  pattern: string;
  job: JobDefinition<EmptyPayload>;
}

export const JOB_SCHEDULES: readonly JobSchedule[] = [
  { id: "cleanup-oauth-requests", pattern: "30 3 * * *", job: cleanupOAuthRequestsJob },
];

// ---------------------------------------------------------------------------------------
// Rate limits
// ---------------------------------------------------------------------------------------

/** At most `max` calls per `windowMs` for one key (a provider, or a provider and connection). */
export interface RateLimit {
  max: number;
  windowMs: number;
}

export interface RateLimitDecision {
  allowed: boolean;
  /** How long to wait before trying again; 0 when allowed. */
  retryAfterMs: number;
}

/**
 * Decides from the counter of the current window. `count` already includes this call and
 * `windowRemainingMs` is the time until the counter resets.
 */
export function decideRateLimit(
  limit: RateLimit,
  count: number,
  windowRemainingMs: number,
): RateLimitDecision {
  if (count <= limit.max) {
    return { allowed: true, retryAfterMs: 0 };
  }
  const remaining = windowRemainingMs > 0 ? windowRemainingMs : limit.windowMs;
  return { allowed: false, retryAfterMs: Math.min(remaining, limit.windowMs) };
}

/** Counter key of a rate limit, e.g. `fio.<connectionId>`. */
export function rateLimitKey(provider: string, scope?: string): string {
  return scope === undefined ? buildJobId(provider) : buildJobId(provider, scope);
}

// ---------------------------------------------------------------------------------------
// Dead letters
// ---------------------------------------------------------------------------------------

/** What is kept about a job that failed for good. No error text: it may quote external data. */
export const deadLetterSchema = z.strictObject({
  queue: z.string(),
  name: z.string(),
  jobId: z.string(),
  data: z.unknown(),
  attemptsMade: z.number().int().nonnegative(),
  errorCode: z.string(),
  failedAt: z.iso.datetime(),
});

export type DeadLetter = z.infer<typeof deadLetterSchema>;

const ERROR_CODE = /^[A-Za-z][A-Za-z0-9_.-]{0,63}$/;

/**
 * Short machine code of an error for logs and dead letters: its `code` if it has a tidy one,
 * otherwise the class name. Never the message, which may contain external or sensitive text.
 */
export function jobErrorCode(error: unknown): string {
  if (typeof error === "object" && error !== null) {
    const { code, name } = error as { code?: unknown; name?: unknown };
    if (typeof code === "string" && ERROR_CODE.test(code)) {
      return code;
    }
    if (typeof name === "string" && ERROR_CODE.test(name)) {
      return name;
    }
  }
  return "unknown_error";
}
