import type { EmailMessage } from "@bystro/core";

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

/** Builds the password-reset e-mail. `url` is the one-time link generated by Better Auth. */
export function resetPasswordEmail(input: { to: string; url: string }): EmailMessage {
  const text = [
    "Ahoj,",
    "",
    "někdo požádal o nové heslo k tvému účtu v Bystru. Nastavíš ho tady:",
    input.url,
    "",
    "Odkaz platí hodinu a jde použít jen jednou.",
    "Pokud jsi o nové heslo nežádal(a), tenhle e-mail smaž. Heslo zůstane stejné.",
    "",
    "Bystro",
  ].join("\n");

  const safeUrl = escapeHtml(input.url);
  const html = [
    "<p>Ahoj,</p>",
    "<p>někdo požádal o nové heslo k tvému účtu v Bystru.</p>",
    `<p><a href="${safeUrl}">Nastavit nové heslo</a></p>`,
    "<p>Odkaz platí hodinu a jde použít jen jednou.</p>",
    "<p>Pokud jsi o nové heslo nežádal(a), tenhle e-mail smaž. Heslo zůstane stejné.</p>",
    "<p>Bystro</p>",
  ].join("\n");

  return { to: input.to, subject: "Nové heslo do Bystra", text, html };
}
